WITH source_cte AS (
    SELECT DISTINCT  
        IFNULL(ss.gapsInCareID, dt.gapsInCareID) AS gapsInCareID,
        IFNULL(ss.yearMonth, dt.yearMonth) AS yearMonth,
        IFNULL(ss.planMemberID, dt.planMemberID) AS planMemberID,
        IFNULL(ss.measureID, dt.measureID) AS measureID,
        IFNULL(ss.subMeasureID, dt.subMeasureID) AS subMeasureID,
        IFNULL(ss.measureCode, dt.measureCode) AS measureCode,
        IFNULL(ss.measureName, dt.measureName) AS measureName,
        IFNULL(ss.numerCnt, dt.numerCnt) AS numerCnt,
        IFNULL(ss.denomCnt, dt.denomCnt) AS denomCnt,
        IFNULL(ss.eventName, dt.eventName) AS eventName,
        IFNULL(ss.dateOfService, dt.dateOfService) AS dateOfService,
        IFNULL(ss.providerID, dt.providerID) AS providerID,
        IFNULL(ss.providerName, dt.providerName) AS providerName,
        IFNULL(ss.dataLoadName, dt.dataLoadName) AS dataLoadName,
        IFNULL(ss.dataFileName, dt.dataFileName) AS dataFileName,
        IFNULL(ss.expectedRate, dt.expectedRate) AS expectedRate,
        IFNULL(ss.serviceNeededByDate, dt.serviceNeededByDate) AS serviceNeededByDate,
        IFNULL(ss.PDC, dt.PDC) AS PDC,
        IFNULL(ss.lastHBVal, dt.lastHBVal) AS lastHBVal,
        IFNULL(ss.lastHBDate, dt.lastHBDate) AS lastHBDate,
        IFNULL(ss.lastBPDia, dt.lastBPDia) AS lastBPDia,
        IFNULL(ss.lastBPSys, dt.lastBPSys) AS lastBPSys,
        IFNULL(ss.lastBPDate, dt.lastBPDate) AS lastBPDate,
        IFNULL(ss.category, dt.category) AS category,
        IFNULL(ss.memberServiceMeasureID, dt.memberServiceMeasureID) AS memberServiceMeasureID,
        IFNULL(ss.memberMeasureID, dt.memberMeasureID) AS memberMeasureID,
        IFNULL(ss.serviceMeasureID, dt.serviceMeasureID) AS serviceMeasureID,
        IFNULL(ss.flaggedEventID, dt.flaggedEventID) AS flaggedEventID,
        IFNULL(ss.pharmacyQualGapID, dt.pharmacyQualGapID) AS pharmacyQualGapID,
        IFNULL(ss.pharmacyQualGapSUPDID, dt.pharmacyQualGapSUPDID) AS pharmacyQualGapSUPDID,
        IFNULL(ss.claimNumber, dt.claimNumber) AS claimNumber,
        IFNULL(ss.creationDateTime, dt.creationDateTime) AS creationDateTime,
        IFNULL(ss.hbTest, dt.hbTest) AS hbTest,
        IFNULL(ss.HashRowKey, dt.HashRowKey) AS HashRowKey,
        CASE 
            WHEN ss.gapsInCareID IS NULL AND dt.gapsInCareID IS NOT NULL THEN 'RecordDelete'
            WHEN ss.gapsInCareID IS NOT NULL AND dt.gapsInCareID IS NULL THEN 'RecordInsert'
            ELSE CASE WHEN ss.HashRowKey <> dt.HashRowKey THEN 'RecordUpdate' END 
        END AS actions
    FROM temptableSQLScript ss 
    FULL OUTER JOIN DestinationTable dt 
        ON IFNULL(ss.gapsInCareID, -1) = IFNULL(dt.gapsInCareID, -1) 
)

MERGE INTO DestinationTable t 
USING source_cte AS S 
    ON IFNULL(S.gapsInCareID, -1) = IFNULL(t.gapsInCareID, -1) 

WHEN MATCHED AND actions = 'RecordUpdate' THEN 
    UPDATE SET 
        t.gapsInCareID = S.gapsInCareID,
        t.yearMonth = S.yearMonth,
        t.planMemberID = S.planMemberID,
        t.measureID = S.measureID,
        t.subMeasureID = S.subMeasureID,
        t.measureCode = S.measureCode,
        t.measureName = S.measureName,
        t.numerCnt = S.numerCnt,
        t.denomCnt = S.denomCnt,
        t.eventName = S.eventName,
        t.dateOfService = S.dateOfService,
        t.providerID = S.providerID,
        t.providerName = S.providerName,
        t.dataLoadName = S.dataLoadName,
        t.dataFileName = S.dataFileName,
        t.expectedRate = S.expectedRate,
        t.serviceNeededByDate = S.serviceNeededByDate,
        t.PDC = S.PDC,
        t.lastHBVal = S.lastHBVal,
        t.lastHBDate = S.lastHBDate,
        t.lastBPDia = S.lastBPDia,
        t.lastBPSys = S.lastBPSys,
        t.lastBPDate = S.lastBPDate,
        t.category = S.category,
        t.memberServiceMeasureID = S.memberServiceMeasureID,
        t.memberMeasureID = S.memberMeasureID,
        t.serviceMeasureID = S.serviceMeasureID,
        t.flaggedEventID = S.flaggedEventID,
        t.pharmacyQualGapID = S.pharmacyQualGapID,
        t.pharmacyQualGapSUPDID = S.pharmacyQualGapSUPDID,
        t.claimNumber = S.claimNumber,
        t.creationDateTime = S.creationDateTime,
        t.hbTest = S.hbTest,
        t.HashRowKey = S.HashRowKey

WHEN MATCHED AND actions = 'RecordDelete' THEN 
    DELETE

WHEN NOT MATCHED AND actions = 'RecordInsert' THEN 
    INSERT (
        gapsInCareID,
        yearMonth,
        planMemberID,
        measureID,
        subMeasureID,
        measureCode,
        measureName,
        numerCnt,
        denomCnt,
        eventName,
        dateOfService,
        providerID,
        providerName,
        dataLoadName,
        dataFileName,
        expectedRate,
        serviceNeededByDate,
        PDC,
        lastHBVal,
        lastHBDate,
        lastBPDia,
        lastBPSys,
        lastBPDate,
        category,
        memberServiceMeasureID,
        memberMeasureID,
        serviceMeasureID,
        flaggedEventID,
        pharmacyQualGapID,
        pharmacyQualGapSUPDID,
        claimNumber,
        creationDateTime,
        hbTest,
        HashRowKey
    )
    VALUES (
        S.gapsInCareID,
        S.yearMonth,
        S.planMemberID,
        S.measureID,
        S.subMeasureID,
        S.measureCode,
        S.measureName,
        S.numerCnt,
        S.denomCnt,
        S.eventName,
        S.dateOfService,
        S.providerID,
        S.providerName,
        S.dataLoadName,
        S.dataFileName,
        S.expectedRate,
        S.serviceNeededByDate,
        S.PDC,
        S.lastHBVal,
        S.lastHBDate,
        S.lastBPDia,
        S.lastBPSys,
        S.lastBPDate,
        S.category,
        S.memberServiceMeasureID,
        S.memberMeasureID,
        S.serviceMeasureID,
        S.flaggedEventID,
        S.pharmacyQualGapID,
        S.pharmacyQualGapSUPDID,
        S.claimNumber,
        S.creationDateTime,
        S.hbTest,
        S.HashRowKey
    );