-- DDL for silver.provider staging table
-- DDL for silver.provider staging table
-- Staged provider demographic/specialty profiles
CREATE TABLE IF NOT EXISTS new.silver.provider (
    BISInternalPersonID string,
    UniqueRecord string,
    ClientID string,
    FileID bigint,
    LoadDateTime timestamp,
    FileLayoutID string,
    FileLayoutDescription string,
    ProviderID string,
    LastName string,
    MiddleInitial string,
    FirstName string,
    TaxonomyCode1 string,
    HpSpecialtyCode1 string,
    ADVProviderSpecialtyCode1 string,
    TaxonomyCode2 string,
    HpSpecialtyCode2 string,
    ADVProviderSpecialtyCode2 string,
    TaxonomyCode3 string,
    HpSpecialtyCode3 string,
    ADVProviderSpecialtyCode3 string,
    TaxonomyCode4 string,
    HpSpecialtyCode4 string,
    ADVProviderSpecialtyCode4 string,
    TaxonomyCode5 string,
    HpSpecialtyCode5 string,
    ADVProviderSpecialtyCode5 string,
    NPI string,
    PrescribePrivilege string,
    DEA string,
    PayorID string,
    Contracted string,
    ProviderHAI string,
    HospitalID string,
    ExcludeFromProviderReporting string,
    AltProvReporting1 string,
    AltProvReporting2 string,
    AltProvReporting3 string,
    AltProvReporting4 string,
    AltProvReporting5 string,
    AltProvReporting6 string,
    AltProvReporting7 string,
    AltProvReporting8 string,
    AltProvReporting9 string,
    AltProvReporting10 string,
    PMUP string,
    IsCurrentPMUP int,
    HashKey string
) USING delta;