INSERT OVERWRITE TABLE claimspan.silver.silver_gapsincare
SELECT 
    -- 1. Autogenerated Keys & Core IDs
    md5(concat_ws('||', clm.member_id, ref.measureCode)) AS memberMeasureID,
    md5(concat_ws('||', clm.member_id, ref.measureCode, ref.eventName)) AS memberServiceMeasureID,
    hash(ref.eventName) AS serviceMeasureID,
    hash(ref.measureCode) AS measureID,
    CAST(NULL AS INT) AS subMeasureID,
    
    -- 2. Metadata & Category Directly From Lookup Table
    ref.measureCode,
    ref.measureName,
    ref.eventName,
    ref.category, -- No massive CASE WHEN needed here anymore!
    
    -- 3. Denominator and Numerator Derivation Logic
    1 AS denomCnt, -- Every matched HEDIS event automatically enters the denominator
    CASE 
        -- If the claim contains a code indicating the service was successfully done
        WHEN clm.medical_code IN ('3074F', '3078F', '83036', '3044F', 'G0108', '90670', '77067', '99213', '99214', '75624-7', '75626-2', '59409', '59514') 
        THEN 1
        ELSE 0 
    END AS numerCnt,
    
    -- 
    -- -- 4. Targets and Dynamic Deadlines
    -- 0.75 AS expectedRate,
    -- to_date(concat(year(clm.service_date), '-12-31')) AS serviceNeededByDate,
    
    -- -- 5. PDC Math Placeholder
    -- CASE 
    --     WHEN ref.measureCode = 'SPD-E' THEN round((clm.days_supply / 365) * 100, 2)
    --     ELSE 0.0 
    -- END AS PDC,
    
    -- edi - mapping - csv - bronze (hedis lookup table) - silver_gapisincare

    -- -- 6. Operational Routing Flags
    -- CASE 
    --     WHEN ref.measureCode IN ('CDC', 'SPD-E') 
    --     THEN concat('PHARM-', md5(concat_ws('||', clm.member_id, ref.measureCode)))
    --     ELSE NULL 
    -- END AS pharmacyQualGapID,
    
    -- CASE 
    --     WHEN ref.measureCode = 'SPD-E' 
    --     THEN concat('SUPD-', md5(concat_ws('||', clm.member_id, ref.measureCode)))
    --     ELSE NULL 
    -- END AS pharmacyQualGapSUPDID,
    
    -- CASE 
    --     WHEN ref.eventName IS NOT NULL 
    --     THEN concat('ESC-', md5(concat_ws('||', clm.member_id, ref.measureCode, ref.eventName)))
    --     ELSE NULL 
    -- END AS flaggedEventID

FROM claimspan.bronze.raw_edi_claims clm
INNER JOIN claimspan.bronze.hedis_measures ref 
    ON clm.medical_code = ref.code;