WITH memAll AS (
    SELECT 
        *,
        ROW_NUMBER() OVER(PARTITION BY BISInternalPersonID ORDER BY LoadDateTime DESC) as rowNum
    FROM member
),

mem AS (
    SELECT 
        BISInternalPersonID,
        uniquePersonKey,
        planMemberID,
        subscriberID,
        beneficiaryID,
        lastName,
        firstName,
        middleInitial,
        enrolleeUniqueID,
        dateofBirth,
        deceasedDate,
        gender,
        permanentAddressLine1,
        permanentAddressLine2,
        permanentCity,
        permanentCounty,
        permanentState,
        permanentZipCode,
        mailingAddressLine1,
        mailingAddressLine2,
        mailingCity,
        mailingState,
        mailingZipCode,
        mailingCounty,
        phoneNumber,
        email,
        medicaidID,
        fax,
        raceCode,
        raceDataSource,
        caretakerFirstName,
        caretakerLastName,
        caretakerMiddleInitial,
        ethnicityCode,
        ethnicityDatasource,
        spokenLanguage,
        spokenLanguagesourcecode,
        writtenLanguageCode,
        writtenLanguageSourcecode,
        otherLanguage,
        otherLanguageSourcecode,
        USCitizen AS isUSCitizen,
        alternateKey1,
        alternateKey2,
        alternateKey3,
        alternateKey4,
        alternateKey5,
        alternateKey6,
        alternateKey7,
        alternateKey8,
        alternateKey9,
        alternateKey10,
        maskedMemberID,
        enrolleeEducation,
        enrolleeEmployment,
        ProductID
    FROM memAll
    WHERE rowNum = 1
)

SELECT 
    CAST(HASH(
        IFNULL(BISInternalPersonID, ""), "|",
        IFNULL(uniquePersonKey, ""), "|",
        IFNULL(planMemberID, ""), "|",
        IFNULL(subscriberID, ""), "|",
        IFNULL(beneficiaryID, ""), "|",
        IFNULL(lastName, ""), "|",
        IFNULL(firstName, ""), "|",
        IFNULL(middleInitial, ""), "|",
        IFNULL(enrolleeUniqueID, ""), "|",
        IFNULL(CAST(dateofBirth AS STRING), ""), "|",
        IFNULL(CAST(deceasedDate AS STRING), ""), "|",
        IFNULL(gender, ""), "|",
        IFNULL(permanentAddressLine1, ""), "|",
        IFNULL(permanentAddressLine2, ""), "|",
        IFNULL(permanentCity, ""), "|",
        IFNULL(permanentCounty, ""), "|",
        IFNULL(permanentState, ""), "|",
        IFNULL(permanentZipCode, ""), "|",
        IFNULL(mailingAddressLine1, ""), "|",
        IFNULL(mailingAddressLine2, ""), "|",
        IFNULL(mailingCity, ""), "|",
        IFNULL(mailingState, ""), "|",
        IFNULL(mailingZipCode, ""), "|",
        IFNULL(mailingCounty, ""), "|",
        IFNULL(phoneNumber, ""), "|",
        IFNULL(email, ""), "|",
        IFNULL(medicaidID, ""), "|",
        IFNULL(fax, ""), "|",
        IFNULL(raceCode, ""), "|",
        IFNULL(raceDataSource, ""), "|",
        IFNULL(caretakerFirstName, ""), "|",
        IFNULL(caretakerLastName, ""), "|",
        IFNULL(caretakerMiddleInitial, ""), "|",
        IFNULL(ethnicityCode, ""), "|",
        IFNULL(ethnicityDatasource, ""), "|",
        IFNULL(spokenLanguage, ""), "|",
        IFNULL(spokenLanguagesourcecode, ""), "|",
        IFNULL(writtenLanguageCode, ""), "|",
        IFNULL(writtenLanguageSourcecode, ""), "|",
        IFNULL(otherLanguage, ""), "|",
        IFNULL(otherLanguageSourcecode, ""), "|",
        IFNULL(isUSCitizen, ""), "|",
        IFNULL(alternateKey1, ""), "|",
        IFNULL(alternateKey2, ""), "|",
        IFNULL(alternateKey3, ""), "|",
        IFNULL(alternateKey4, ""), "|",
        IFNULL(alternateKey5, ""), "|",
        IFNULL(alternateKey6, ""), "|",
        IFNULL(alternateKey7, ""), "|",
        IFNULL(alternateKey8, ""), "|",
        IFNULL(alternateKey9, ""), "|",
        IFNULL(alternateKey10, ""), "|",
        IFNULL(maskedMemberID, ""), "|",
        IFNULL(enrolleeEducation, ""), "|",
        IFNULL(enrolleeEmployment, ""), "|",
        IFNULL(ProductID, "")
    ) AS BIGINT) AS memberKey,
    *,
    CURRENT_DATE() AS effectiveStartDate,
    CAST(NULL AS DATE) AS effectiveEndDate,
    TRUE AS isCurrent
FROM mem;