CREATE OR REPLACE TABLE claimspan.gold.gold_memberRevenueGap (
   identifier_planMemberID string,
   hccNumber string,
   reportMonth string,
   clientCode string,
   name_given_first string,
   name_family string,
   birthDate string,
   hccVersion string,
   hccDescription string,
   ESAIInternalProviderID string,
   identifier_npi string,
   provider_name_family string,
   provider_name_given_first string,
   practiceCode string,
   practiceName string,
   market string,
   alertCategory string,
   closureReason string,
   lastDCConfirmedDate date,
   lastPCPVisitDate date,
   lastAWVDate date,
   snapshotDate date,
   identifier_planID string,
   hashKey string
) USING delta;