CREATE TABLE IF NOT EXISTS claimspan.silver.silver_member (
  ESAIInternalPersonID string
, UniqueRecord string
, ClientID string
, FileID int
, LoadDateTime date
, FileLayoutID int
, FileLayoutDescription string
, identifier_enrolleeUniqueID string
, identifier_planMemberID string
, identifier_subscriberID string
, identifier_beneficiaryID string
, name_family string
, name_given_first string
, name_given_middle string
, birthDate string
, deceasedDateTime string
, gender string
, address_permanent_line1 string
, address_permanent_line2 string
, address_permanent_city string
, address_permanent_district string
, address_permanent_state string
, address_permanent_postalCode string
, address_mailing_line1 string
, address_mailing_line2 string
, address_mailing_city string
, address_mailing_state string
, address_mailing_postalCode string
, address_mailing_district string
, telecom_phone_home string
, telecom_email string
, identifier_medicaidID string
, telecom_fax string
, extension_race_text string
, extension_race_dataSource string
, contact_caretaker_name_given_first string
, contact_caretaker_name_family string
, contact_caretaker_name_given_middle string
, extension_ethnicity_ombCategory_code string
, extension_ethnicity_dataSource string
, communication_spokenLanguage_text string
, communication_spokenLanguage_codeSystem string
, communication_writtenLanguage_code string
, communication_writtenLanguage_codeSystem string
, communication_otherLanguage_text string
, communication_otherLanguage_codeSystem string
, extension_usCitizenStatus string
, identifier_alternateKey1 string
, identifier_alternateKey2 string
, identifier_alternateKey3 string
, identifier_alternateKey4 string
, identifier_alternateKey5 string
, identifier_alternateKey6 string
, identifier_alternateKey7 string
, identifier_alternateKey8 string
, identifier_alternateKey9 string
, identifier_alternateKey10 string
, extension_maskedMemberID string
, extension_enrolleeEducation string
, extension_enrolleeEmployment string
, PMUP string
, IsCurrentPMUP int
, extension_coverageProduct_id string
, name_prefix string
, name_suffix string
, name_text string
, HashKey string
) USING delta;
