-- 1. PROCESSING: Define staging view using actual CSV headers mapped to target schema where applicable
CREATE TEMPORARY STREAMING LIVE VIEW stg_gapsincare_processed
AS SELECT 
    esaiinternalpersonid AS ESAIInternalPersonID,
    uniquepersonkey AS identifier_uniquepersonkey,
    planmemberid AS identifier_planMemberID,
    subscriberid AS identifier_subscriberID,
    beneficiaryid AS identifier_beneficiaryID,
    enrolleeuniqueid AS identifier_enrolleeUniqueID,
    lastname AS name_family,
    firstname AS name_given_first,
    middleinitial AS name_given_middle,
    dateofbirth AS birthDate,
    deceaseddate AS deceasedDateTime,
    gender AS gender,
    permanentaddressline1 AS address_permanent_line1,
    permanentaddressline2 AS address_permanent_line2,
    permanentcity AS address_permanent_city,
    permanentcounty AS address_permanent_district,
    permanentstate AS address_permanent_state,
    permanentzipcode AS address_permanent_postalCode,
    mailingaddressline1 AS address_mailing_line1,
    mailingaddressline2 AS address_mailing_line2,
    mailingcity AS address_mailing_city,
    mailingstate AS address_mailing_state,
    mailingzipcode AS address_mailing_postalCode,
    mailingcounty AS address_mailing_district,
    phonenumber AS telecom_phone_home,
    email AS telecom_email,
    medicaidid AS identifier_medicaidID,
    fax AS telecom_fax,
    racecode AS extension_race_text,
    racedatasource AS extension_race_dataSource,
    caretakerfirstname AS contact_caretaker_name_given_first,
    caretakerlastname AS contact_caretaker_name_family,
    caretakermiddleinitial AS contact_caretaker_name_given_middle,
    ethnicitycode AS extension_ethnicity_ombCategory_code,
    ethnicitydatasource AS extension_ethnicity_dataSource,
    spokenlanguage AS communication_spokenLanguage_text,
    spokenlanguagesourcecode AS communication_spokenLanguage_codeSystem,
    writtenlanguagecode AS communication_writtenLanguage_code,
    writtenlanguagesourcecode AS communication_writtenLanguage_codeSystem,
    otherlanguage AS communication_otherLanguage_text,
    otherlanguagesourcecode AS communication_otherLanguage_codeSystem,
    isuscitizen AS extension_usCitizenStatus,
    alternatekey1 AS identifier_alternateKey1,
    alternatekey2 AS identifier_alternateKey2,
    alternatekey3 AS identifier_alternateKey3,
    alternatekey4 AS identifier_alternateKey4,
    alternatekey5 AS identifier_alternateKey5,
    alternatekey6 AS identifier_alternateKey6,
    alternatekey7 AS identifier_alternateKey7,
    alternatekey8 AS identifier_alternateKey8,
    alternatekey9 AS identifier_alternateKey9,
    alternatekey10 AS identifier_alternateKey10,
    maskedmemberid AS extension_maskedMemberID,
    enrolleeeducation AS extension_enrolleeEducation,
    enrolleeemployment AS extension_enrolleeEmployment,
    productid AS extension_coverageProduct_id,
    iscurrent AS IsCurrentPMUP,
    measureName AS measureName,
    measureSource AS measureSource,
    CAST(NULL AS STRING) AS measurecode,
    CAST(NULL AS STRING) AS eventName,
    care_gap_status AS careGapStatus,
    evaluation_date AS evaluationDate,
    CAST(NULL AS STRING) AS gapsInCareID,
    CAST(NULL AS STRING) AS dateOfService,
    CAST(NULL AS STRING) AS serviceNeededByDate,
    CAST(NULL AS STRING) AS lastHBDate,
    CAST(NULL AS INT) AS numerCnt,
    CAST(NULL AS INT) AS denomCnt,
    CAST(NULL AS STRING) AS practitioner_identifier,
    CAST(NULL AS DOUBLE) AS expectedRate,
    CAST(NULL AS DOUBLE) AS PDC,
    CAST(NULL AS DOUBLE) AS lastHBVal,
    CAST(NULL AS DOUBLE) AS lastBPDia,
    CAST(NULL AS DOUBLE) AS lastBPSys,
    CAST(NULL AS STRING) AS identifier_claimnumber,
    CAST(NULL AS STRING) AS hbTest,
    HASH(CONCAT_WS('||', 
        IFNULL(memberkey, ''), 
        IFNULL(planmemberid, ''), 
        IFNULL(measureName, ''), 
        IFNULL(evaluation_date, '')
    )) AS HashKey
FROM STREAM(LIVE.caregapreport);

-- 2. TARGET TABLE: Create target streaming Delta table shell
CREATE OR REFRESH STREAMING TABLE silver_gapsincare;

-- 3. CDC MERGE: Apply changes using updated primary keys
APPLY CHANGES INTO LIVE.silver_gapsincare
FROM STREAM(LIVE.stg_gapsincare_processed)
KEYS (identifier_planMemberID, measureName, evaluationDate)
SEQUENCE BY evaluationDate
STORED AS SCD TYPE 1;