SELECT
    GapsInCareID AS gapsInCareID,
    YearMonth AS yearMonth,
    MemberKey AS planMemberID,
    MeasureID AS measureID,
    SubMeasureID AS subMeasureID,
    MeasureCode AS measureCode,
    MeasureName AS measureName,
    NumerCnt AS numerCnt,
    DenomCnt AS denomCnt,
    EventName AS eventName,
    DateOfService AS dateOfService,
    ProviderKey AS providerID,
    ProviderName AS providerName,
    DataLoadName AS dataLoadName,
    DataFileName AS dataFileName,
    ExpectedRate AS expectedRate,
    ServiceNeededByDate AS serviceNeededByDate,
    PDC AS PDC,
    LastHBVal AS lastHBVal,
    LastHBDate AS lastHBDate,
    LastBPDia AS lastBPDia,
    LastBPSys AS lastBPSys,
    LastBPDate AS lastBPDate,
    Category AS category,
    MemberServiceMeasureID AS memberServiceMeasureID,
    MemberMeasureID AS memberMeasureID,
    ServiceMeasureID AS serviceMeasureID,
    FlaggedEventID AS flaggedEventID,
    PharmacyQualGapID AS pharmacyQualGapID,
    PharmacyQualGapSUPDID AS pharmacyQualGapSUPDID,
    Claimnumber AS claimNumber,
    CreationDateTime AS creationDateTime,
    HBTest AS hbTest,
    HASH(CONCAT(
        IFNULL(GapsInCareID, ""),
        IFNULL(YearMonth, ""),
        IFNULL(MemberKey, ""),
        IFNULL(MeasureID, ""),
        IFNULL(SubMeasureID, ""),
        IFNULL(MeasureCode, ""),
        IFNULL(MeasureName, ""),
        IFNULL(NumerCnt, ""),
        IFNULL(DenomCnt, ""),
        IFNULL(EventName, ""),
        IFNULL(DateofService, ""),
        IFNULL(ProviderKey, ""),
        IFNULL(ProviderName, ""),
        IFNULL(DataLoadName, ""),
        IFNULL(DataFileName, ""),
        IFNULL(ExpectedRate, ""),
        IFNULL(ServiceNeededByDate, ""),
        IFNULL(PDC, ""),
        IFNULL(LastHBVal, ""),
        IFNULL(LastHBDate, ""),
        IFNULL(LastBPDia, ""),
        IFNULL(LastBPSys, ""),
        IFNULL(LastBPDate, ""),
        IFNULL(Category, ""),
        IFNULL(MemberServiceMeasureID, ""),
        IFNULL(MemberMeasureID, ""),
        IFNULL(ServiceMeasureID, ""),
        IFNULL(FlaggedEventID, ""),
        IFNULL(PharmacyQualGapID, ""),
        IFNULL(PharmacyQualGapSUPDID, ""),
        IFNULL(Claimnumber, ""),
        IFNULL(CreationDateTime, ""),
        IFNULL(HBTest, "")
    )) AS HashRowKey
FROM gapsInCare;