WITH Type2ProvidersToUpdate AS (
  SELECT 
    CAST(NULL AS STRING) AS pID,
    a.*
  FROM tempSQLScript a
  INNER JOIN DestinationTable t 
    ON a.ESAIInternalProviderID = t.practitionerIdentifier
   AND a.providerKey <> t.providerKey
   AND t.isCurrent = 1
),
AllProvidersFromSource AS (
  SELECT 
    a.ESAIInternalProviderID AS pID,
    a.*
  FROM tempSQLScript a
),
ProvidersCombined AS (
  SELECT * FROM Type2ProvidersToUpdate
  UNION ALL
  SELECT * FROM AllProvidersFromSource
)
MERGE INTO DestinationTable t 
USING ProvidersCombined s 
   ON s.pID = t.practitionerIdentifier 
  AND t.isCurrent = 1
WHEN MATCHED AND s.providerKey <> t.providerKey THEN UPDATE SET 
  t.effectiveEndDate = CURRENT_DATE(),
  t.isCurrent = 0 
WHEN NOT MATCHED THEN INSERT ( 
  providerKey,
  practitionerIdentifier,
  effectiveStartDate,
  effectiveEndDate,
  isCurrent,
  identifierNpi,
  identifierDea,
  nameFamily,
  nameGivenFirst,
  nameGivenMiddle,
  telecomPhone,
  addressLine1,
  addressLine2,
  addressCity,
  addressState,
  addressPostalCode,
  practiceCode,
  locationPracticeName,
  providerOrgCode,
  organizationName,
  identifierTin,
  hospitalIdentifier,
  providerSpecialtyDescription,
  taxonomyCode1,
  taxonomyCode2,
  taxonomyCode3,
  taxonomyCode4,
  taxonomyCode5,
  hpSpecialtyCode1,
  advProviderSpecialtyCode1,
  hpSpecialtyCode2,
  advProviderSpecialtyCode2,
  hpSpecialtyCode3,
  advProviderSpecialtyCode3,
  hpSpecialtyCode4,
  advProviderSpecialtyCode4,
  hpSpecialtyCode5,
  advProviderSpecialtyCode5,
  isPrescribePrivilege,
  payerIdentifier,
  isContracted,
  providerHai,
  isExcludedFromProviderReporting,
  programType,
  practiceTargetedStatus,
  productIdentifier,
  providerType,
  altProvReporting1,
  altProvReporting2,
  altProvReporting3,
  altProvReporting4,
  altProvReporting5,
  altProvReporting6,
  altProvReporting7,
  altProvReporting8,
  altProvReporting9,
  altProvReporting10
) VALUES ( 
  s.providerKey,
  s.ESAIInternalProviderID,
  s.effectiveStartDate,
  s.effectiveEndDate,
  s.isCurrent,
  s.identifier_npi,
  s.identifier_providerDEA,
  s.name_family,
  s.name_given_first,
  s.name_given_middle,
  s.telecom_phone,
  s.address_line1,
  s.address_line2,
  s.address_city,
  s.address_state,
  s.address_postalCode,
  s.practiceCode,
  s.practiceName,
  s.providerOrgCode,
  s.providerOrgName,
  s.identifier_tin,
  s.identifier_hospitalID,
  s.providerSpecialtyDescription,
  s.taxonomyCode1,
  s.taxonomyCode2,
  s.taxonomyCode3,
  s.taxonomyCode4,
  s.taxonomyCode5,
  s.hpSpecialtyCode1,
  s.advProviderSpecialtyCode1,
  s.hpSpecialtyCode2,
  s.advProviderSpecialtyCode2,
  s.hpSpecialtyCode3,
  s.advProviderSpecialtyCode3,
  s.hpSpecialtyCode4,
  s.advProviderSpecialtyCode4,
  s.hpSpecialtyCode5,
  s.advProviderSpecialtyCode5,
  s.extension_isPrescribePrivilege,
  s.identifier_payerID,
  s.extension_isContracted,
  s.extension_providerHAI,
  s.extension_isExcludedFromProviderReporting,
  s.extension_programType,
  s.extension_practiceTargetedStatus,
  s.extension_ProductID,
  s.extension_ProviderType,
  s.identifier_alternateKey1,
  s.identifier_alternateKey2,
  s.identifier_alternateKey3,
  s.identifier_alternateKey4,
  s.identifier_alternateKey5,
  s.identifier_alternateKey6,
  s.identifier_alternateKey7,
  s.identifier_alternateKey8,
  s.identifier_alternateKey9,
  s.identifier_alternateKey10
);